### ISSUE TITLE
Incorrect maximal rectangle on concave polygon

### ISSUE THREAD

**Issue by toqitahamid** [planetlabs/maxrect#6]
My coordinates are - 

[[1825, 1208],
 [1826, 1207],
 [1878, 1195],
 [1933, 1242],
 [1994, 1254],
 [2103, 1218],
 [2127, 1287],
 [2189, 1314],
 [2187, 1360],
 [2036, 1429],
 [1967, 1433],
 [1913, 1371],
 [1898, 1276]]

But I am getting this - 

![image](https://user-images.githubusercontent.com/2114722/61411413-524f0200-a8b4-11e9-8177-26f67dfc72d4.png)

**Comment by dnstankiewicz** [comment]
Hi, did you managed to solve this? I'm facing same issue...

**Comment by dnstankiewicz** [comment]
Ok, so in order to get better result you need quite simple convex polygon. 
If it is too complicate, algorithm is getting lost so it would be best to firstly apply convex_hull operation on polygon.
